// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7_zUGWyEjKcIePvma9_m6CL01yiNpxt8',
    appId: '1:946988847170:web:c90c73671eab70a0ad1ddb',
    messagingSenderId: '946988847170',
    projectId: 'mainor-2025-weather-app',
    authDomain: 'mainor-2025-weather-app.firebaseapp.com',
    storageBucket: 'mainor-2025-weather-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVK_UiXy1qBcV1eBiULQbkZcSsM8CFKt0',
    appId: '1:946988847170:android:a461ccfe785878afad1ddb',
    messagingSenderId: '946988847170',
    projectId: 'mainor-2025-weather-app',
    storageBucket: 'mainor-2025-weather-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC39IJ18yvuI83Vl8vvA-hYzevetSIJbMQ',
    appId: '1:946988847170:ios:6a36a17808c3e436ad1ddb',
    messagingSenderId: '946988847170',
    projectId: 'mainor-2025-weather-app',
    storageBucket: 'mainor-2025-weather-app.firebasestorage.app',
    iosBundleId: 'com.mainor.weather.weatherMainorApp',
  );
}
